from PyQt5.QtWidgets import ( QWidget, QPushButton, QLabel,  QVBoxLayout, QApplication, QTableWidget, QListWidget, QListWidgetItem,
QLineEdit, QFormLayout, QHBoxLayout, QVBoxLayout, QGroupBox, QButtonGroup, QRadioButton, QPushButton, QLabel, QSpinBox)
from PyQt5.QtCore import Qt
app=QApplication([])
b_menu =QPushButton("Menu") 
b_sleep =QPushButton("Rest")
box_min = QSpinBox()
box_min.setValue(30)
b_ok = QPushButton("answer")
l_question = Qlabel("")
rb1 = QRadioButton("")
rb2 = QRadioButton("")
rb3 = QRadioButton("")
rb4 = QRadioButton("")

radio_group = QGroupBox("Variants of answers")
radio_group = QRadioButton()
radio_group.addButton(rb1)
radio_group.addButton(rb2)
radio_group.addButton(rb3)
radio_group.addButton(rb4)

ans_group_box = QGroupBox("results of test")
l_result = QLabel("")
l_correct = QLabel("")
lineH = QHBoxLayout()
lineV1 = QVBoxLayout()
lineV2 = QVBoxLayout()
lineV1.addWidget(rb1)
lineV1.addWidget(rb2)
lineV2.addWidget(rb3)
lineV2.addWidget(rb4)